spring:
  application:
    name: role-service
server:
  port: ${PORT:8101}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: 
     defaultZone: https://ms-eureka-server.herokuapp.com/eureka
  instance:
    hostname: ms-eureka-server.herokuapp.com